-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 22:55:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXIST  ` site ` ;
USE `site` ;

-- -----------------------------------------------------
-- Table `CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `CATEGORIA` (
  `NomeCategoria` VARCHAR(35) NOT NULL,
  `idCATEGORIA` INT NOT NULL,
  PRIMARY KEY (`NomeCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUBCATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUBCATEGORIA` ;

CREATE TABLE IF NOT EXISTS `SUBCATEGORIA` (
  `TituloSUBCATEGORIA` VARCHAR(45) NOT NULL,
  `NomeCATEGORIA` VARCHAR(40) NOT NULL,
  `URL` VARCHAR(85) NOT NULL,
  `Texto` LONGTEXT NULL,
  PRIMARY KEY (`TituloSUBCATEGORIA`),
  CONSTRAINT `fk_SUBCATEGORIA_CATEGORIA`
    FOREIGN KEY (`NomeCATEGORIA`)
    REFERENCES `CATEGORIA` (`NomeCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(16) NOT NULL,
  `UsuarioNOME` VARCHAR(45) NOT NULL,
  `RUA` VARCHAR(45) NOT NULL,
  `NumeroRES` INT NOT NULL,
  `ComplementoRES` VARCHAR(15) NOT NULL,
  `CEP` INT NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(14) NULL,
  `NumeroCARTAO` VARCHAR(16) NOT NULL,
  `CVC` CHAR(3) NOT NULL,
  `DataValidade` DATE NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
